# Generated by Django 3.2 on 2021-04-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=0, max_digits=20)),
                ('circulating_supply', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
    ]
